spring:
  main:
    allow-bean-definition-overriding: true


server:
  port: 50300
macro:
  security:
    client:
      client-id: macro-security-server
      client-secret: 123456
      token-header: x-client-token
      expired: 8640000
logging:
  level:
    wang.sunnly: debug
