spring:
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: sunnly-modules-logger
          uri: lb://sunnly-modules-logger
          order: 8000
          predicates:
            - Path=/logger/**
          filters:
            - StripPrefix=1
        - id: macro-auth
          uri: lb://macro-auth
          order: 8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: macro-admin
          uri: lb://macro-admin
          order: 8000
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
server:
  port: 20020