spring:
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: sunnly-modules-logger
          uri: lb://sunnly-modules-logger
          order: 8000
          predicates:
            - Path=/logger/**
          filters:
            - StripPrefix=1
        - id: macro-auth
          uri: lb://macro-auth
          order: 8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: macro-admin
          uri: lb://macro-admin
          order: 8000
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
server:
  port: 20020
logging:
  level:
    wang.sunnly.modules.gateway: debug

macro:
  gate:
    startWith:
      ignores:
#       获取登录页面系统配置
        - /auth/sys/system
#        验证码
        - /auth/code/
        - /auth/jwt/token
  feign:
    client:
      admin: macro-admin
  security:
    user:
      token-header: Authorization
      rsa-secret: 123456
      #      secret: 123456
      expired: 8640000
    client:
      #      数据库中id和secret
      client-id: macro-auth
      rsa-secret: rsaClientSecret
      secret: 123456
      rsa: true
      token-header: x-client-token
