spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://mysql.sunnly.wang:3306/macro_auth?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: sunnly
    props:
      sql.show: true
  redis:
    host: redis.sunnly.wang
    database: 1

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true

server:
  port: 20010
macro:
  feign:
    client:
      admin: macro-admin