spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://mysql.sunnly.wang:3306/macro_auth?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: sunnly
    props:
      sql.show: true
  redis:
    host: redis.sunnly.wang
    database: 1
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true

server:
  port: 20010
macro:
  feign:
    client:
      admin: macro-admin

  validate:
    code:
      image:
        font-size: 32

  mail:
    from:
      accout: 389943100@qq.com
      password: cwfrvlqkvcgvcabi

#  jwt:
#    user:
#      token-header: Authorization
#      secret: 123456
#      expired: 8640000
  user:
    locked:
      count: 5
      timeout: 5

  security:
    user:
      token-header: Authorization
      rsa-secret: 123456
#      secret: 123456
      expired: 8640000
    client:
#      数据库中id和secret
      client-id: macro-auth
      rsa-secret: rsaClientSecret
      #      secret: 123456
      #      feign头
      secret: 123456
      token-header: x-client-token

logging:
  level:
    wang.sunnly: debug
