macro:
  sunnly:
    test1: sdfdsf
    test2: '{cipher}AQBLXzNpBPMY/e46y1RIBw32488NDHeS13givLJFIzSD9y8H8ddEo5FO/Hapb8OOIZWL/iCVgq358ljx2TfTYw+uREyNLLAKUHCU0LQFOJvTuePZDhv4DFWcVuPYB6psCv6OB7tYJa8m1Ki/UMiiVcWZlnIY24LI5hjk0iBoq/4ZyzAvpjJLywYnd2ir50LJ9vNrYFSyLtuVjhTNzuY6CYTFL2JFFzt0tObQEhXJ6EQ5fPo+vLlPHOK7o9kdljf0RcfkASEdjTIRl7iiejn7Y7sNLXlIqVhhwwGskaLePgEJOTzOmRVi+4ZV9od45O9HalsS4LBKMsaeoda8ApdsOFyXy4zED8XlyPR/I3+TTimg2u/i75KeTz+38GX1AbHOr/0='