spring:
  cloud:
    gateway:
      routes:
        - id: sunnly-modules-logger
          uri: lb://sunnly-modules-logger
          order: 8000
          predicates:
            - Path=/logger/**
          filters:
            - StripPrefix=1
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false