server:
  port: 20030
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://mysql.sunnly.wang:3306/macro_admin?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: sunnly
    props:
      sql.show: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true

macro:
  jwt:
    user:
      token-header: Authorization
      secret: 123456
#      expired: 86400
