spring:
  main:
    allow-bean-definition-overriding: true


server:
  port: 20060
#macro:
#  feign:
#    client:
#      admin: macro-admin
#
#  validate:
#    code:
#      image:
#        font-size: 32
#
#  mail:
#    from:
#      accout: 389943100@qq.com
#      password: cwfrvlqkvcgvcabi
#
#  jwt:
#    user:
#      token-header: Authorization
#      secret: 123456
#      expired: 8640000
#  user:
#    locked:
#      count: 5
#      timeout: 5

